fix(ld-input): prop forwarding
emdgroup-liquid/liquid pull request #169
Opened 2021-11-30 15:57 UTC by renet

References:
  - #157

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] unit tests
- [x] tested manually

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

2021-11-30 16:46 UTC, borisdiakur requested changes

2021-11-30 16:46 UTC, borisdiakur commented on src/liquid/utils/__mocks__/cloneAttributes.ts
> +  // @ts-ignore
What exactly are we ignoring here?
> It is recommended practice to have the remainder of the comment following @ts-ignore explain which error is being suppressed.

2021-12-01 10:46 UTC, renet commented on src/liquid/utils/__mocks__/cloneAttributes.ts
> +  // @ts-ignore
Done.

2021-12-01 10:48 UTC, merged

2021-12-02 19:00 UTC, borisdiakur commented
:tada: This PR is included in version 1.0.0-rc.19 :tada:

The release is available on:
- [npm package (@rc dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.0.0-rc.19)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.0.0-rc.19)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-02-09 14:00 UTC, borisdiakur commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.0.0)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: