fix(ld-checkbox): prop forwarding and indeterminate state
emdgroup-liquid/liquid pull request #174
Opened 2021-12-01 16:47 UTC by borisdiakur

References:
  - #157

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] unit tests
- [x] e2e tests
- [x] tested manually

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

2021-12-02 13:22 UTC, renet requested changes

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-checkbox/ld-checkbox.tsx
> +  @Prop() list?: string
Does this prop make sense for a checkbox?

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-radio/ld-radio.tsx
> +  @Prop() list?: string
Same as for checkbox.

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-radio/ld-radio.tsx
>    @Watch('required')
Same as for input/checkbox.

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-radio/ld-radio.tsx
> +      this.hiddenInput = document.createElement('input')
Same as for checkbox. (type/style)
```suggestion
      this.hiddenInput = document.createElement('input')
      this.hiddenInput.type = 'radio'
      this.hiddenInput.style.visibility = 'hidden'
      this.hiddenInput.style.position = 'absolute'
      this.hiddenInput.style.pointerEvents = 'none'
```

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-radio/ld-radio.tsx
>        if (this.name) {
Same as for checkbox.
```suggestion
    if (this.name && (outerForm || this.form)) {
```

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-radio/test/ld-radio.spec.ts
> +      html: `<form><ld-radio name="example" /></form>`,
Same as for checkbox.

```
jest.mock('../../../utils/cloneAttributes')
```

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-toggle/ld-toggle.tsx
> +  /** The input value. */
Same as above, wrong description.

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-toggle/ld-toggle.tsx
> +  @Prop() list?: string
Same as above.

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-toggle/ld-toggle.tsx
>    @Watch('required')
Same as above.

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-toggle/ld-toggle.tsx
> +      this.hiddenInput = document.createElement('input')
Same as for checkbox/radio.

```suggestion
      this.hiddenInput = document.createElement('input')
      this.hiddenInput.type = 'checkbox'
      this.hiddenInput.style.visibility = 'hidden'
      this.hiddenInput.style.position = 'absolute'
      this.hiddenInput.style.pointerEvents = 'none'
```

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-toggle/ld-toggle.tsx
>        if (this.name) {
Same.

```suggestion
    if (this.name && (outerForm || this.form)) {
```

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-toggle/test/ld-toggle.spec.ts
> +      html: `<form><ld-toggle name="example" /></form>`,
Same.

```
jest.mock('../../../utils/cloneAttributes')
```

2021-12-02 13:22 UTC, renet commented on src/liquid/components/ld-toggle/ld-toggle.tsx
`cloneAttibutes` is missing here completely!

2021-12-02 14:39 UTC, borisdiakur commented on src/liquid/components/ld-checkbox/ld-checkbox.tsx
>    /** The input value. */
Wait, why is this wrong? I just copied this from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

2021-12-02 14:51 UTC, renet commented on src/liquid/components/ld-checkbox/ld-checkbox.tsx
>    /** The input value. */
Because you're describing the "checked" prop here...

2021-12-02 16:03 UTC, renet requested changes

2021-12-02 16:03 UTC, renet commented on src/liquid/components/ld-radio/ld-radio.tsx
> +      this.el.appendChild(this.hiddenInput)
```suggestion
```

2021-12-02 16:03 UTC, renet commented on src/liquid/components/ld-toggle/ld-toggle.tsx
> +      this.el.appendChild(this.hiddenInput)
```suggestion
```

2021-12-02 16:54 UTC, renet approved these changes

2021-12-02 16:55 UTC, merged

2021-12-02 18:59 UTC, borisdiakur commented
:tada: This PR is included in version 1.0.0-rc.19 :tada:

The release is available on:
- [npm package (@rc dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.0.0-rc.19)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.0.0-rc.19)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-02-09 14:00 UTC, borisdiakur commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.0.0)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: