fix(ld-tabs): show tabpanel according to preselected tab
emdgroup-liquid/liquid pull request #184
Opened 2021-12-08 14:13 UTC by borisdiakur

Fixes #179

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] unit tests
- [x] tested manually in React app

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

2021-12-08 22:23 UTC, renet requested changes

2021-12-08 22:23 UTC, renet commented on src/liquid/components/ld-tabs/ld-tabs.tsx
> +      ) {
```suggestion
      if (tab.selected) {
```

2021-12-09 11:10 UTC, borisdiakur commented on src/liquid/components/ld-tabs/ld-tabs.tsx
> +      ) {
Changed ⚡️

2021-12-09 11:16 UTC, renet approved these changes

2021-12-09 13:25 UTC, merged

2021-12-14 10:06 UTC, borisdiakur commented
:tada: This PR is included in version 1.0.0-rc.21 :tada:

The release is available on:
- [npm package (@rc dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.0.0-rc.21)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.0.0-rc.21)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-02-09 14:00 UTC, borisdiakur commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.0.0)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: