docs: add data visualization, restructure pages
emdgroup-liquid/liquid pull request #301
Opened 2022-04-07 18:00 UTC by renet

# Description

Adds 'Data Visualization' section with IFrame content and restructures the *.md files that generate the docs pages.

## Type of change

- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] tested manually

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass locally with my changes

2022-04-08 09:00 UTC, renet commented on src/docs/components/docs-iframe/docs-iframe.css
> +    calc(var(--docs-nav-width))
```suggestion
    var(--docs-nav-width)
```

2022-04-08 09:56 UTC, borisdiakur requested changes

2022-04-08 09:56 UTC, borisdiakur commented on src/liquid/components/index.md
> +  order: 4
I would put data visialization below components.

2022-04-08 10:35 UTC, borisdiakur approved these changes

2022-04-08 10:51 UTC, merged

2022-04-12 13:16 UTC, borisdiakur commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.5.0)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: