feat(ld-sidenav): integrate accordion with sidenav
emdgroup-liquid/liquid pull request #314
Opened 2022-04-14 12:51 UTC by borisdiakur

# Description

This PR integrates the ld-accordion component and its subcomponents into the ld-sidenav component.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] unit tests
- [ ] e2e tests
- [ ] accessibility tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

2022-04-27 13:44 UTC, renet requested changes

2022-04-27 15:39 UTC, borisdiakur commented on src/liquid/components/ld-accordion/ld-accordion-toggle/ld-accordion-toggle.tsx
> +   * your own focusable element inside the toggle label element.
The prop is only used in split mode, so there should be no issue.

2022-04-28 19:41 UTC, borisdiakur commented on src/liquid/components/ld-sidenav/readme.md
> +{% example '{ "hasPadding": false, "styles": { "minHeight": "30rem", "position": "relative" } }' %}
This is now implemented. You can use the `split` prop on the `ld-sidenav-accordion` element in order to activate two separate click areas. Default is now one large toggle button.

2022-04-29 11:23 UTC, borisdiakur commented on src/liquid/components/ld-sidenav/ld-sidenav-accordion/ld-sidenav-accordion.tsx
> +    }
Changed the default behavior offering an option to disable preserving the state of the accordion.

2022-04-29 11:59 UTC, renet approved these changes

2022-04-29 11:59 UTC, renet commented on src/liquid/components/ld-sidenav/ld-sidenav-accordion/ld-sidenav-accordion.tsx
> +              }
Why not using a modifier class for `ld-sidenav-accordion__accordion-panel` instead of inline styles?

2022-04-29 14:51 UTC, closed without merging