Feat/ld breadcrumbs
emdgroup-liquid/liquid pull request #340
Opened 2022-05-10 12:58 UTC by Tabanion

# Description
Added new `ld-breadcrumbs` component.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] unit tests
- [ ] e2e tests
- [ ] accessibility tests
- [ ] tested manually
- [ ] other:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

2022-05-17 15:38 UTC, renet requested changes

2022-05-17 15:38 UTC, renet commented on src/liquid/components/ld-link/ld-link.tsx
> +        part="a"
Can we please name it "link" or at least "anchor"? `::part(a)` may be a little confusing for a maintainer. - Also, shouldn't it also have the part "focusable" (and implement the InnerFocusable interface)?

2022-05-18 08:25 UTC, borisdiakur commented on src/liquid/components/ld-link/ld-link.css
> +  }
The link PR has already been approve with this approach, which I still find is legit. I will not change this due to the reasons mentioned plus the additional effort to change everything.

2022-05-18 09:55 UTC, renet commented on src/liquid/components/ld-link/ld-link.css
> +  }
Please add the comment, as discussed in the review. Then this conversation can be resolved.

2022-05-18 09:56 UTC, renet approved these changes
LGTM subject to the open conversations.

2022-05-18 13:21 UTC, merged

2022-05-18 17:03 UTC, borisdiakur commented
:tada: This PR is included in version 1.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.11.0)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: