refactor: new design tokens and color variables
emdgroup-liquid/liquid pull request #56
Opened 2021-10-28 15:57 UTC by renet

# Description

Uses new design tokens in a way that makes design tokens and themes exchangeable.

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] E2E Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-02 15:02 UTC, borisdiakur requested changes

2021-11-02 15:23 UTC, renet commented on src/docs/components/docs-topbar/docs-topbar.css
> +  background-color: var(--ld-thm-primary);
```suggestion
  background-color: var(--ld-col-rp);
```

2021-11-02 15:23 UTC, renet commented on src/docs/includes/layout.njk
> +<body class="ld-theme-bubblegum">
```suggestion
<body>
```

2021-11-02 15:26 UTC, borisdiakur approved these changes

2021-11-02 15:31 UTC, renet commented on src/liquid/global/styles/global.css
> +@import '../../components/ld-heading/ld-heading.global.css';
```suggestion
```

2021-11-02 15:37 UTC, merged

2022-02-09 14:04 UTC, borisdiakur commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.0.0)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: