feat(ld-context-menu): add context menu component
emdgroup-liquid/liquid pull request #568
Opened 2023-03-13 12:28 UTC by renet

# Description

Adds a new `ld-context-menu` component, as well as additional modes for the `ld-button` component and necessary changes to the `ld-tooltip` component.

BREAKING CHANGE: danger-secondary now requires secondary class, too.

Fixes #438

## Type of change

Please delete options that are not relevant.

- [x] Feature
- [x] Bugfix
- [x] Refactoring (no functional changes, no api changes)
- [x] Documentation content changes

## Is it a breaking change?

- [ ] Yes
- [x] No

# How Has This Been Tested?

Please describe the tests that you've added and run to verify your changes. 
Provide instructions, so we can reproduce.

- [x] unit tests
- [x] e2e tests
- [x] accessibility tests
- [x] tested manually

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] New and existing tests pass locally with my changes

2023-03-13 15:28 UTC, borisdiakur requested changes
I haven't checked the code yet. But there are two things that I found when testing the component on preview:

1. When I focus a context menu item and press the Tab button, I land in Nirvana. I recommend preventing the default in this case.
2. The screen reader currently doesn't give any hint on focus of a context menu trigger button. Please add `aria-haspopup="menu"` to the trigger button programmatically.

It would be great if you could address these two points before I dive deeper into the code review.

2023-03-14 12:00 UTC, borisdiakur requested changes

2023-03-15 13:46 UTC, renet commented on src/liquid/components/ld-tooltip/ld-tooltip.tsx
> +          aria-describedby={
Will postpone this to a separate PR.

2023-03-30 08:00 UTC, renet commented on src/liquid/components/ld-context-menu/ld-menu/ld-menu.tsx
> +  private focusByFirstCharacter = (event: KeyboardEvent) => {
I finished unifying and centralizing the typeahead feature for both select and context menu components. There is one intended difference, though: in the context menu, a new search starts at the item following the currently focused item. this way I can find/focus all menu items that match a certain character or string, not only the first one. Please take a look at the implementation - there also were some "bugs" in the select component that differed from the native select behavior that have been fixed during the refactoring.

2023-03-30 09:44 UTC, borisdiakur requested changes

2023-03-30 09:44 UTC, borisdiakur commented on src/liquid/components/ld-context-menu/ld-menu/readme.md
> +  <ld-menuitem>Menum item 1</ld-menuitem>
```suggestion
  <ld-menuitem>Menu item 1</ld-menuitem>
```

2023-03-30 09:44 UTC, borisdiakur commented on src/liquid/utils/keyboard-navigation.ts
> +  /* Clear timeout */
```suggestion
```

2023-03-30 12:12 UTC, borisdiakur approved these changes

2023-03-30 14:32 UTC, merged