feat(ld-select): use up-to-date css custom props
emdgroup-liquid/liquid pull request #59
Opened 2021-11-03 14:29 UTC by borisdiakur

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-05 13:04 UTC, renet requested changes

2021-11-05 13:04 UTC, renet commented on src/liquid/components/ld-select/ld-option-internal/ld-option-internal.css
> +  --ld-option-thm-col-bg-active: var(--ld-thm-primary-alpha-lowest);
I discussed this with Nic, as the design uses`--ld-col-rb-010` (a new color added when Nic updated the colors in Figma), which is not a valid theme color. Still waiting for feedback, but I suggest to not change colors in this refectoring, if these changes do not reflect the design, unless Nic agrees. :)

2021-11-05 13:07 UTC, renet commented on src/liquid/components/ld-select/ld-option-internal/ld-option-internal.css
> +  --ld-option-thm-col-bg-active: var(--ld-thm-primary-alpha-lowest);
PS: Shouldn't these changes result in updates on the screenshots? Are we missing an e2e tests that test these specific states, or am I missing something?

2021-11-08 13:25 UTC, renet commented on src/liquid/components/ld-select/ld-option-internal/ld-option-internal.css
> +  --ld-option-thm-col-bg-active: var(--ld-thm-primary-alpha-lowest);
```suggestion
  --ld-option-thm-col-bg-hover: var(--ld-thm-primary-highlight);
  --ld-option-thm-col-bg-focus: var(--ld-thm-primary-highlight);
  --ld-option-thm-col-bg-active: var(--ld-thm-primary-highlight);
```

Should now do the job without changing the color at all.

2021-11-08 14:33 UTC, borisdiakur commented on src/liquid/components/ld-select/ld-select.css
> +        box-shadow: inset 0 0 0 0.1rem var(--ld-select-invalid-col);
This one is also used as a box-shadow color. I'll keep it as it is.

2021-11-08 14:34 UTC, borisdiakur commented on src/liquid/components/ld-select/ld-select.css
> +      color: var(--ld-select-invalid-col);
This one is also used as a box-shadow color. I'll keep it as it is.

2021-11-08 14:38 UTC, borisdiakur commented on src/liquid/components/ld-select/ld-select.css
> +  --ld-select-invalid-col-active: var(--ld-thm-error-active);
I wouldn't over-engineer things here. If I really want to know what --ld-select-invalid-col is applied to, I make a quick search in the file. This is only component internal stuff, so I think it's fine as it is.

2021-11-08 14:40 UTC, borisdiakur commented on src/liquid/components/ld-select/ld-select.css
> +  --ld-select-ghost-thm-bg-col-focus: var(--ld-thm-primary-alpha-low);
You're deleting --ld-select-thm-col although it's in use?

2021-11-08 16:34 UTC, renet commented on src/liquid/components/ld-select/ld-select.css
> +  --ld-select-ghost-thm-bg-col-focus: var(--ld-thm-primary-alpha-low);
Oh, my bad. I just searched in the diff, not the whole file. 😅

2021-11-08 16:35 UTC, renet commented on src/liquid/components/ld-select/ld-select.css
> +  --ld-select-ghost-thm-bg-col-focus: var(--ld-thm-primary-alpha-low);
Updated the suggestion.

2021-11-08 16:37 UTC, renet approved these changes

2021-11-08 16:38 UTC, merged

2022-02-09 14:04 UTC, borisdiakur commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@emdgroup-liquid/liquid/v/1.0.0)
- [GitHub release](https://github.com/emdgroup-liquid/liquid/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: