fix(ld-select): wait for popper to be visible before focusing filter
emdgroup-liquid/liquid pull request #814
Opened 2023-07-10 14:02 UTC by borisdiakur

# Description

It looks like the Tether enable method returns before the actual popper element is visible. So we need to "wait" for it to become visible before setting the focus on the filter input element.

Fixes #813

## Type of change

- [x] Bugfix

## Is it a breaking change?

- [x] No

# How Has This Been Tested?

- [x] tested manually

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] New and existing tests pass locally with my changes

2023-07-10 14:50 UTC, renet requested changes

2023-07-10 14:50 UTC, renet commented on src/liquid/components/ld-select/ld-select.tsx
> +  }
This potentially results in very many calls of this iterative function. Maybe even something like a stack overflow, as this may run endlessly? Maybe adding a short debounce wrapper and limiting the amount of tries would be helpful?

And is there really no way to get notified as soon as rendering is done? 🙈

2023-07-11 06:24 UTC, dpitois commented on src/liquid/components/ld-select/ld-select.tsx
> +  }
Don't know how it could be applied here, but maybe [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) can be used to listen to the style change?

2023-07-11 09:54 UTC, borisdiakur commented on src/liquid/components/ld-select/ld-select.tsx
> +  }
I have implemented a version using MutationObserver and it works well. However, it'll take some time for me to adjust all tests as we now need to mock MutationObserver logic for multiple observers and trigger their callbacks in the tests independently. I'm working on it.

2023-07-11 12:30 UTC, renet approved these changes
It's really a pity that Stencil doesn't have a better solution for this. 😢

2023-07-11 12:46 UTC, merged